services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis